include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    avoid_print: ignore
    avoid_catches_without_on_clauses: ignore
    public_member_api_docs: ignore
