name: projection_cs
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  dart_jts: ^0.3.0+1

  flutter:
    sdk: flutter

  latlong2: ^0.9.1
  proj4dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
