name: projection_cs
description: A Dart package for coordinate system transformations using the Proj4 library.
version: 1.0.0
homepage: https://github.com/Cagdassrgl/projection_cs
repository: https://github.com/Cagdassrgl/projection_cs

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_jts: ^0.3.0+1

  flutter:
    sdk: flutter

  latlong2: ^0.9.1
  proj4dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
